[tool.poetry]
name = "proyecto-imdb"
version = "0.1.0"
description = ""
authors = ["Jesús Solís <63575551+Jesolis14@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
